### PR TITLE
Fixing slow nonlinear convergence for URIS valve

### LINKED ISSUE #448: Slow nonlinear convergence when using URIS valve in fluid equation
### Description

Nonlinear convergence in the [`uris` valve test case](https://github.com/SimVascular/svMultiPhysics/tree/main/tests/cases/uris/pipe_uris_3d) is very bad. Here is the convergence history for the 5th timestep when running on 4 processors

```
FS 5-1  1.049e+02  [0 1.000e+00 2.828e+01 9.680e-05]  [175 -2 4]
 MS 5-1  1.054e+02  [0 1.000e+00 7.349e-02 8.745e-05]  [48 -2 3]
 FS 5-2  1.067e+02  [-19 1.077e-01 3.045e+00 9.532e-05]  [94 -9 9]
 MS 5-2  1.072e+02  [-81 8.745e-05 6.426e-06 9.295e-05]  [53 -2 4]
 FS 5-3  1.084e+02  [-28 3.918e-02 1.108e+00 9.985e-05]  [44 -92 4]
 MS 5-3  1.089e+02  [-161 8.128e-09 5.973e-10 6.585e-03]  [28 0 2]
 FS 5-4  1.100e+02  [-30 2.888e-02 8.168e-01 9.879e-05]  [34 -92 3]
 MS 5-4  1.106e+02  [-205 5.353e-11 3.934e-12 1.000e+00]  [0 0 0]
 FS 5-5  1.118e+02  [-32 2.469e-02 6.985e-01 9.812e-05]  [34 -92 3]
 MS 5-5  1.123e+02  [-205 5.353e-11 3.934e-12 1.000e+00]  [0 0 0]
 FS 5-6  1.137e+02  [-33 2.180e-02 6.165e-01 9.941e-05]  [49 -92 5]
 MS 5-6  1.142e+02  [-205 5.353e-11 3.934e-12 1.000e+00]  [0 0 0]
 FS 5-7  1.155e+02  [-34 1.949e-02 5.512e-01 9.813e-05]  [88 -6 9]
 MS 5-7  1.160e+02  [-205 5.353e-11 3.934e-12 1.000e+00]  [0 0 0]
 FS 5-8  1.174e+02  [-35 1.756e-02 4.967e-01 9.833e-05]  [82 -4 7]
 MS 5-8  1.178e+02  [-205 5.353e-11 3.934e-12 1.000e+00]  [0 0 0]
 FS 5-9  1.197e+02  [-35 1.591e-02 4.500e-01 9.991e-05]  [85 -5 10]
 MS 5-9  1.207e+02  [-205 5.353e-11 3.934e-12 1.000e+00]  [0 0 0]
 FS 5-10s 1.234e+02  [-36 1.448e-02 4.095e-01 9.886e-05]  [85 -5 9]
```
The `mesh` (MS) equation converges well, but the `fsi` (FS) equation is very bad. 

### Reproduction

Run the [uris test case](https://github.com/SimVascular/svMultiPhysics/tree/main/tests/cases/uris/pipe_uris_3d) and observe the nonlinear convergence in the history file.

### Expected behavior

Convergence should be theoretically quadratic for Newton's method.

### Additional context

From what I can tell from the fluid assembly equations in `fluid.cpp`, the URIS valve term in the fluid equation is treated essentially the same as the Brinkman term for porous media. Therefore, the poor convergence for URIS is likely related to the [poor convergence for porous media](https://github.com/SimVascular/svMultiPhysics/issues/357). I think it is reasonably likely there is a linearization bug or missing linearization term that affects both these cases.

Currently, the fluid assembly equations (e.g. [`fluid_3d_m()`](https://github.com/SimVascular/svMultiPhysics/blob/277dd0665e0aff69d09a89f32d4d82f58d87ed7d/Code/Source/solver/fluid.cpp#L1468)) are very hard to follow and do not clearly map to any written documentation. Excellent papers exist, including [Basilevs et al. (2007) ](https://www-sciencedirect-com.stanford.idm.oclc.org/science/article/pii/S0045782507003027), which I think is probably the basis for the residual-based VMS formulation of the Navier-Stokes equations currently implemented in svMultiPhysics. For Navier-Stokes-Brinkman, which is more relevant to this issue, there is [Gerosa et al. (2024) ](https://www-sciencedirect-com.stanford.idm.oclc.org/science/article/pii/S0045782524001981?fr=RR-2&ref=pdf_download&rr=9870bcc4fcfe67cd#sec3) (Fannie's paper), which cites [Fuchsberger et al. (2022)](https://www-sciencedirect-com.stanford.idm.oclc.org/science/article/pii/S1877750321001691#sec2). [The Overleaf document for svMultiPhysics theory](https://www.overleaf.com/project/66df3023609a6369d54d481b) could also be helpful, although I believe there are some errors/inconsistencies and it does not discuss the Navier-Stokes-Brinkman equation.

To aid this debugging effort, I thought it would be helpful to refactor the fluid assembly equations to be more readable and to map directly to these literature. @ktbolt @mrp089 @zasexton @hanzhao2020  Curious to hear your thoughts if this is worth it, and how this might interact with other refactoring efforts.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by hanzhao2020**
## Current situation
Resolves https://github.com/SimVascular/svMultiPhysics/issues/448

## Release Notes 
* Fixed the stagnated nonlinear convergence for the RIS valve in CFD simulations by removing the `up` term in the RIS formulation in `fluid.cpp`.
* Improved the slow nonlinear convergence for the RIS valve in FSI simulations by implementing the explicit geometric coupling approach in `pic.cpp`. In each time step of the FSI simulation, the fluid–structure equation is solved to nonlinear convergence with fixed mesh displacement from the previous time step, then the mesh equation is solved.
* Updated test cases for the URIS valve with CFD and FSI simulations.

## Code of Conduct & Contributing Guidelines 
- [x] I agree to follow the [Code of Conduct](https://github.com/SimVascular/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/SimVascular/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: Code/Source/solver/fluid.cpp [hunk 1]
```diff
@@ -2239,11 +2239,11 @@ void fluid_3d_m(ComMod& com_mod, const int vmsFlag, const int eNoNw, const int e
...
   for (int a = 0; a < eNoNw; a++) {
       lR(0,a) = lR(0,a) + mu*K_inverse_darcy_permeability*w*Nw(a)*(u[0]+up[0])
-                        + Res*DDir*w*Nw(a)*(u[0]+up[0]);
+                        + Res*DDir*w*Nw(a)*(u[0]);
       lR(1,a) = lR(1,a) + mu*K_inverse_darcy_permeability*w*Nw(a)*(u[1]+up[1])
-                        + Res*DDir*w*Nw(a)*(u[1]+up[1]);
+                        + Res*DDir*w*Nw(a)*(u[1]);
       lR(2,a) = lR(2,a) + mu*K_inverse_darcy_permeability*w*Nw(a)*(u[2]+up[2])
-                        + Res*DDir*w*Nw(a)*(u[2]+up[2]);
+                        + Res*DDir*w*Nw(a)*(u[2]);
```
Comment (ktbolt) [inline Code/Source/solver/fluid.cpp]: @hanzhao2020 Remove the extra `()`

**Review by ktbolt — APPROVED** [review]
@hanzhao2020 Looks ok to me.

File: Code/Source/solver/pic.cpp [hunk 2]
```diff
@@ -143,7 +143,7 @@ void picc(Simulation* simulation)
     pic_eth(simulation);
   }
 
-  if (eq.phys == Equation_FSI) {
+  if (eq.phys == Equation_FSI && !eq.expl_geom_cpl) {
```
Comment (aabrown100-git) [inline Code/Source/solver/pic.cpp]: Could you add some comments to this code to explain what's going on?

**Review by aabrown100-git — CHANGES_REQUESTED** [review]
@hanzhao2020 Looks good thanks for this! Just a couple comments.

BTW, I have already tested these changes (using Han's latest branch which also includes some other changes) with my recent cardiac FSI simulations and I can confirm greatly improved nonlinear convergence.

File: tests/cases/uris/pipe_uris_3d/result_005.vtu
Comment (aabrown100-git) [inline tests/cases/uris/pipe_uris_3d/result_005.vtu]: Just for the sake of future developers, can you comment how different the results are after removing the `up` term. Also, for FSI, how different are the results between implicit and explicit geometric coupling?

**Review by aabrown100-git — APPROVED** [review]
@hanzhao2020 Looks good to me, thanks!
